name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    steps:
      - uses: actions/checkout@v4
      - name: Update apt
        run: sudo apt-get update
      - name: Set up dependencies
        run: sudo apt-get install build-essential cmake lsb-release ninja-build
      - name: Build
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_EXPORT_COMPILE_COMMANDS=On -DCMAKE_GENERATOR=Ninja
          cmake --build build/
      - name: Run unit tests
        run: cmake --build build/ --target test
