name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update apt
        run: sudo apt-get update
      - name: Set up dependencies
        run: sudo apt-get install build-essential cmake wget lsb-release
      - name: Build
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=On
          cmake --build build/
      - name: Run unit tests
        run: cmake --build build/ --target test
